export const initMainPageState = {
  isLoading: false,
  error: '',
  cards: [],
  searchValue: localStorage.getItem('searchValue') || '',
  isSearchApplied: false,
  currentCard: null,
  isPinInfo: false,
  cardsPerPage: '1',
  sortingType: 'relevance',
  nextPage: undefined,
  prevPage: undefined,
  currentPage: undefined,
  pagesCount: 0,
  currentPageNumber: 1,
};
